version: '3'
services:
  ethereum-node:
    image: rosenkaramanov/go-ethereum:latest
    pull_policy: always
    container_name: ethereum-node
    ports:
      - "8545:8545" # JSON-RPC
      - "30303:30303" # P2P communication
    networks:
      - devnet
    volumes:
      - ./hardhat:/app/hardhat # Mount the hardhat directory
    command: ["sh", "-c", "
      # Start Ethereum node in development mode
      geth --dev --rpc --rpcaddr 0.0.0.0 --rpcport 8545 --rpcapi web3,eth,debug,personal,net,miner,admin &
      # Wait for the Ethereum node to start up (adjust timing as needed)
      sleep 10 &&
      # Install dependencies (e.g., Hardhat and dependencies)
      cd /app/hardhat && npm install &&
      # Run Hardhat tests
      npx hardhat test --network devnet
      npx hardhat run scripts/deploy.js --network localhost
    "]


networks:
  devnet:
    driver: bridge