version: '3'
services:
  ethereum-node:
    image: rosenkaramanov/go-ethereum:latest
    pull_policy: always
    container_name: ethereum-node
    ports:
      - "8545:8545" # JSON-RPC
      - "30303:30303" # P2P communication
    volumes:
      - ./hardhat:/app/hardhat # Mount the hardhat directory
    command:
      [
        "--dev",                       # Run in developer mode
        "--http",                      # Enable JSON-RPC over HTTP
        "--http.addr", "0.0.0.0",      # Allow access from any address
        "--http.port", "8545",         # RPC port
        "--http.api", "eth,web3,net",  # Enable APIs for RPC
        "--allow-insecure-unlock"      # Allow accounts to be unlocked
      ]

networks:
  devnet:
    driver: bridge