name: Deploy and Test on Devnet

on:
  pull_request:
    types: [closed]
    branches:
      - master
    labels:
      - 'CI:Deploy'

jobs:
  deploy-and-test:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'CI:Deploy') # Add this condition
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Install Docker Compose
        run: |
            sudo curl -L "https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            docker-compose --version
        continue-on-error: false

      - name: Start Local Devnet
        run: docker-compose up

      - name: Build and Push Devnet Image with Contracts
        run: |
          docker commit ethereum-node rosenkaramanov/go-ethereum:with-contracts
          docker push rosenkaramanov/go-ethereum:with-contracts