name: Deploy to AWS EKS

on:
  pull_request:
    types: [closed]
    branches:
      - master
    labels:
      - 'CI:DeployProd'
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'CI:DeployProd') #Trigger if CI:DeployProd tag is present

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: cd terraform && terraform init

      - name: Terraform Plan
        run: cd terraform && terraform plan

      - name: Terraform Apply
        run: cd terraform && terraform apply -auto-approve

      - name: Set up Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
          helm version

      - name: Set up Repo
        run: |
          helm repo add rosen-helm-charts https://rosenkrmnv.github.io/helm-charts/
          helm repo list

      - name: Deploy Helm chart
        run: |
          helm upgrade --install go-ethereum-chart rosen-helm-charts/go-ethereum-deployment --namespace default
